site_name: xPro-v5
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md 
  - Quick Start: quickStart.md
  - Troubleshoot: troubleshoot.md
